name: Compare current and previous versions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compare-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: yaroslavzghoba/compare-versions@1.0.2
        with:
          # The URL of the repository to clone.
          repo-clone-url: 'https://${{ secrets.PAT_FOR_CLONING }}@github.com/yaroslavzghoba/material-color-utilities-kotlin.git'

          # Bash commands that should extract the version from the code.
          versions-extractor: |
            chmod u+x ./gradlew
            ./gradlew wrapper > /dev/null
            ./gradlew printVersion -q

          # The shell to use for running the commands.
          shell: 'bash'